version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "uni-prop-local-contract"
s3_prefix = "uni-prop-local-contract"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"Local\""

[default.build.parameters]
beta_features = true

[default.sync.parameters]
beta_features = true
