version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "uni-prop-local-properties"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"Local\""
s3_prefix = "uni-prop-local-properties"
resolve_s3 = true

region = "us-east-1"

[default.build.parameters]
beta_features = true

[default.sync.parameters]
beta_features = true