name: Build & Test Workflow
on:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/*'
      - 'unicorn_shared/**'
      - 'unicorn_contracts/**'
      - 'unicorn_approvals/**'
      - 'unicorn_web/**'

permissions:
  contents: read

jobs:
  unicorn-service:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      PYTHON_VERSION: "3.13"
      NODE_VERSION: "24.x"

    strategy:
      # max-parallel: 1
      matrix:
        service:
        - name: unicorn_contracts
          service_template_path: unicorn_contracts/infrastructure/contracts-service
        - name: unicorn_approvals
          service_template_path: unicorn_approvals/infrastructure/approvals-service
        - name: unicorn_web
          service_template_path: unicorn_web/infrastructure/web-service

    steps:
    - uses: actions/checkout@v6

    - run: echo "**** Setup Python ****"
    - name: Setup Python
      uses: actions/setup-python@v6.2.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - run: python --version

    - run: echo "**** Install Python based tooling ****"
    - name: Install Python based tooling
      run: pip install cfn-lint cfn-lint-serverless

    - run: echo "**** Setup NodeJS ****"
    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: 'echo "NodeJS version: $(node --version)"'
  
    - run: echo "**** Setup pnpm ****"
    - uses: pnpm/action-setup@v4.2.0
      with:
        version: 10
    - run: 'echo "pnpm version: $(pnpm --version)"'

    - run: echo "**** Install NodeJS based tooling ****"
    - name: Install NodeJS based tooling
      run: npm install -g esbuild 

    - run: echo "**** Install application dependencies ****"
    - name: Install application dependencies
      run: pnpm install --no-frozen-lockfile
      working-directory: ${{ matrix.service.name }}

    - name: Run cfn-lint and cfn-lint-serverless
      run: cfn-lint template.yaml -a cfn_lint_serverless.rules
      working-directory: ${{ matrix.service.service_template_path }}

    - name: Run Unit Tests
      if: ${{ matrix.service.name != 'unicorn_web' }}
      run: pnpm test tests/unit
      working-directory: ${{ matrix.service.name }}
